// Code generated by logcopter-gen; DO NOT EDIT.

package engine

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.zine-layout.pkg.imagelayout.engine")
