// Code generated by logcopter-gen; DO NOT EDIT.

package layoutsequences

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.zine-layout.cmd.zine-layout.cmds.api.layout_sequences")
