// Code generated by logcopter-gen; DO NOT EDIT.

package imagelayouttemplatescmd

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.zine-layout.cmd.zine-layout.cmds.workflow.image_layout_templates")
