// Code generated by logcopter-gen; DO NOT EDIT.

package renderer

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.zine-layout.pkg.pagelayout.renderer")
