// Code generated by logcopter-gen; DO NOT EDIT.

package services

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.zine-layout.pkg.services")
