// Code generated by logcopter-gen; DO NOT EDIT.

package imagelayouttemplates

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.zine-layout.cmd.zine-layout.cmds.api.image_layout_templates")
